# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake

# The command to remove a file.
RM = /home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/davirap/ws/ops-build/src/ops-hw-config

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/davirap/ws/ops-build/src/ops-hw-config

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/davirap/ws/ops-build/build/tmp/sysroots/x86_64-linux/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davirap/ws/ops-build/src/ops-hw-config/CMakeFiles /home/davirap/ws/ops-build/src/ops-hw-config/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/davirap/ws/ops-build/src/ops-hw-config/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named config-yaml

# Build rule for target.
config-yaml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config-yaml
.PHONY : config-yaml

# fast build rule for target.
config-yaml/fast:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/build
.PHONY : config-yaml/fast

#=============================================================================
# Target rules for targets named cfg_yaml_ut

# Build rule for target.
cfg_yaml_ut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cfg_yaml_ut
.PHONY : cfg_yaml_ut

# fast build rule for target.
cfg_yaml_ut/fast:
	$(MAKE) -f tests/CMakeFiles/cfg_yaml_ut.dir/build.make tests/CMakeFiles/cfg_yaml_ut.dir/build
.PHONY : cfg_yaml_ut/fast

src/config-yaml.o: src/config-yaml.cpp.o
.PHONY : src/config-yaml.o

# target to build an object file
src/config-yaml.cpp.o:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/config-yaml.cpp.o
.PHONY : src/config-yaml.cpp.o

src/config-yaml.i: src/config-yaml.cpp.i
.PHONY : src/config-yaml.i

# target to preprocess a source file
src/config-yaml.cpp.i:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/config-yaml.cpp.i
.PHONY : src/config-yaml.cpp.i

src/config-yaml.s: src/config-yaml.cpp.s
.PHONY : src/config-yaml.s

# target to generate assembly for a file
src/config-yaml.cpp.s:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/config-yaml.cpp.s
.PHONY : src/config-yaml.cpp.s

src/i2c.o: src/i2c.c.o
.PHONY : src/i2c.o

# target to build an object file
src/i2c.c.o:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/i2c.c.o
.PHONY : src/i2c.c.o

src/i2c.i: src/i2c.c.i
.PHONY : src/i2c.i

# target to preprocess a source file
src/i2c.c.i:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/i2c.c.i
.PHONY : src/i2c.c.i

src/i2c.s: src/i2c.c.s
.PHONY : src/i2c.s

# target to generate assembly for a file
src/i2c.c.s:
	$(MAKE) -f CMakeFiles/config-yaml.dir/build.make CMakeFiles/config-yaml.dir/src/i2c.c.s
.PHONY : src/i2c.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... config-yaml"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cfg_yaml_ut"
	@echo "... src/config-yaml.o"
	@echo "... src/config-yaml.i"
	@echo "... src/config-yaml.s"
	@echo "... src/i2c.o"
	@echo "... src/i2c.i"
	@echo "... src/i2c.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
